name: Docker Questions CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    name: Build and Push Questions Docker images

    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:

    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Checkout
      uses: actions/checkout@v4

    - name: Build Docker questions-editor
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/questions-editor:latest .

    - name: Push Docker questions-editor
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/questions-editor:latest

    - name: Build Docker questions-editor-jobs
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/questions-editor-jobs:latest -f Dockerfile.jobs .

    - name: Jobs changes
      run: |
        git fetch origin main
        if git diff --name-only origin/main HEAD | grep -q '^jobs/'; then
          echo "push_jobs=true" >> $GITHUB_ENV
        else
          echo "No changes detected in the specific folder"
          echo "push_jobs=false" >> $GITHUB_ENV

    - name: Push Docker questions-editor-jobs
      if: env.push_jobs == 'true'
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/questions-editor-jobs:latest
