name: Docker Questions CI

on:
  push:
    branches: [ "main", "actions" ]

jobs:

  build:
    name: Build and Push Questions Docker images

    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:

    # - name: Docker Login
    #   uses: docker/login-action@v3.3.0
    #   with:
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}

    # - name: Checkout
    #   uses: actions/checkout@v4

    # - name: Build Docker questions-editor
    #   run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/questions-editor:latest .

    # - name: Build Docker questions-editor-jobs
    #   run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/questions-editor-jobs:latest -f Dockerfile.jobs .

    - uses: dorny/paths-filter@v3
      id: changes
      with:
        filters: |
          jobs:
            - 'jobs/**'

    - name: log test true
       if: steps.changes.outputs.jobs == 'true'
       run: echo "There's a thing in my code!"

    - name: log test false
       if: steps.changes.outputs.jobs == 'false'
       run: echo "false"

    # - name: Push Docker questions-editor
    #   run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/questions-editor:latest

    # - name: Push Docker questions-editor-jobs
    #   if: steps.changes.outputs.jobs == 'true'
    #   run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/questions-editor-jobs:latest
