name: Docker Image CI

on:
  push:
    branches: [ "main", "actions" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      secrets: read

    steps:
    - name: Debug secrets
      run: echo "Username ${{ secrets.DOCKERHUB_USERNAME }}"
        
    - name: Log in to Docker Hub
      run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - uses: actions/checkout@v4
    - name: Build Docker questions-editor
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/questions-editor:latest .

    - name: Push Docker questions-editor
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/image1:latest
