name: Docker Image CI

on:
  push:
    branches: [ "main", "actions" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
    - name: Debug secrets
      run: echo "Username ${{ secrets.DOCKERHUB_USERNAME }} and ${{ secrets.DOCKERHUB_TOKEN }}"
        
    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
          
    - uses: actions/checkout@v4
    - name: Build Docker questions-editor
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/questions-editor:latest .

    - name: Push Docker questions-editor
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/image1:latest
