name: Docker Questions Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    name: Build and Push Questions Images

    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:

    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Checkout
      uses: actions/checkout@v4

    - name: Build Docker questions-editor
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/questions-editor:latest .

    - name: Push Docker questions-editor
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/questions-editor:latest
